sudo: false
language: node_js
node_js:
- stable
install:
- npm install
after_success:
- npm run jsdoc
- npm run gh-pages-travis
env:
  global:
  - SSH_KEY="githubsdk"
  - GIT_NAME="Daniel Mariño"
  - GIT_EMAIL="changete@gmail.com"
  - SOURCE_DIR="doc"
  - DEPLOY_BRANCH="master"
deploy:
  skip_cleanup: true
  provider: npm
  email: YOUR_EMAIL_ADDRESS
  api_key: YOUR_API_KEY
  on:
    branch: master
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_b5f2f80f1338_key -iv $encrypted_b5f2f80f1338_iv
  -in githubsdk.enc -out ~\/Desktop/TouchvieSDK/material/keys/githubsdk -d
